name: dev_deploy

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: q-n-a_deploy
  IMAGE_TAG: master

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./development
          push: true
          platforms: linux/amd64, linux/arm64
          tags: ghcr.io/q-n-a-dev-team/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  scan:
    name: Scan Image Vulnerability
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull docker image
        run: docker pull ghcr.io/q-n-a-dev-team/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: Container image scan
        uses: Azure/container-scan@v0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ghcr.io/q-n-a-dev-team/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy:
    name: Push on traP Git
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: https://dev-q-n-a.trap.games/
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > ~/deploy_key
          chmod 600 ~/deploy_key
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "Q'n'A-dev"
      - name: Place showcase.yml on root
        run: |
          mv development/showcase.yaml .
          git add .
          git commit -m "Deploy dev"
      - name: Push on traP Git
        env:
          GIT_SSH_COMMAND: ssh -i ~/deploy_key -o StrictHostKeyChecking=no -F /dev/null
        run: |
          git fetch --unshallow origin
          git push -f ssh://git@git.trap.jp:2200/Q-n-A-dev-team/Q-n-A_dev.git master
